apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nfts.nft.acnodal.com
  namespace: arbf-operators
spec:
  group: nft.acnodal.com
  names:
    kind: Nft
    listKind: NftList
    plural: nfts
    singular: nft
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
--- 
apiVersion: nft.acnodal.com/v1alpha1
kind: Nft
metadata:
  name: nft
  annotations:
    "ansible.operator-sdk/verbosity": "4" 
  namespace: arbf-operators
spec:
  public_nic: enp1s0
  enable_dropall: false
  enable_ssh: true
  enable_bgp: true 
  enable_rateshape: true
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arbf-nft-operator
  namespace: arbf-operators
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arbf-nft-operator
subjects:
- kind: ServiceAccount
  namespace: arbf-operators
  name: arbf-nft-operator
roleRef:
  kind: ClusterRole
  name: arbf-nft-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: arbf-nft-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - services/status
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - arbf-nft-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - nft.acnodal.com
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arbf-nft-operator
  namespace: arbf-operators
spec:
  replicas: 1
  selector:
    matchLabels:
      name: arbf-nft-operator
  template:
    metadata:
      labels:
        name: arbf-nft-operator
    spec:
      serviceAccountName: arbf-nft-operator
      containers:
        - name: ansible
          command:
          - /usr/local/bin/ao-logs
          - /tmp/ansible-operator/runner
          - stdout
          image: "acnodal/nft-operator:v0.0.1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
            readOnly: true
          - name: ssh-key
            mountPath: /tmp/key
            readOnly: true
        - name: operator
          image: "acnodal/nft-operator:v0.0.1"
          imagePullPolicy: "Always"
          volumeMounts:
          - mountPath: /tmp/ansible-operator/runner
            name: runner
          - name: ssh-key
            mountPath: /tmp/key
            readOnly: true
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "arbf-nft-operator"
            - name: ANSIBLE_GATHERING
              value: explicit
      volumes:
        - name: runner
          emptyDir: {}
        - name: ssh-key
          secret:
            secretName: ansible-operator-ssh

