apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nfts.nft.acnodal.com
spec:
  group: nft.acnodal.com
  names:
    kind: Nft
    listKind: NftList
    plural: nfts
    singular: nft
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
