kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arbf-nft-operator
subjects:
- kind: ServiceAccount
  namespace: arbf-operators
  name: arbf-nft-operator
roleRef:
  kind: ClusterRole
  name: arbf-nft-operator
  apiGroup: rbac.authorization.k8s.io
